baseURL = "https://dalnoboy-dev.pages.dev/"
languageCode = "ru-ru"
defaultContentLanguage = "ru"
title = "Дальнобойный Программист"
theme = "coder"

[languages]
  [languages.ru]
    languageName = "Русский"
    title = "Дальнобойный Программист"
    weight = 1

    [languages.ru.menu]
      [[languages.ru.menu.main]]
        name = "О себе"
        weight = 1
        url = "/about/"
      [[languages.ru.menu.main]]
        name = "Блог"
        weight = 2
        url = "/posts/"
      [[languages.ru.menu.main]]
        name = "Проекты"
        weight = 3
        url = "/projects/"
      [[languages.ru.menu.main]]
        name = "Связаться со мной"
        weight = 4
        url = "/contact/"
      [[languages.ru.menu.main]]
        name = "RU"
        weight = 5
        url = "/"

    [languages.ru.params]
      avatarURL = "/images/avatar.jpg"
      avatarSize = "300px"